-- Datos iniciales de ejemplo para desarrollo y pruebas: CIE-10, vademécum y su relación N a N.
-- No sustituyen un catálogo oficial. Los nombres de medicamentos y las casas comerciales son genéricos o ficticios.
-- Idempotente: se puede ejecutar varias veces sin duplicar filas. No fija ids: las relaciones se
-- resuelven por cie10.codigo y vademecum.nombre (los nombres de este archivo son únicos).
-- Contenido: 100 diagnósticos (14 categorías), 100 medicamentos (9 casas comerciales), 244 relaciones.

-- 1. cie10 (100 filas). codigo tiene UNIQUE (uk_cie10_codigo).
INSERT INTO cie10 (codigo, descripcion, categoria) VALUES
    ('A07.1', 'Giardiasis [lambliasis]', 'Ciertas enfermedades infecciosas y parasitarias'),
    ('A08.4', 'Infección intestinal viral, sin otra especificación', 'Ciertas enfermedades infecciosas y parasitarias'),
    ('A09', 'Diarrea y gastroenteritis de presunto origen infeccioso', 'Ciertas enfermedades infecciosas y parasitarias'),
    ('A90', 'Fiebre del dengue [dengue clásico]', 'Ciertas enfermedades infecciosas y parasitarias'),
    ('B01.9', 'Varicela sin complicaciones', 'Ciertas enfermedades infecciosas y parasitarias'),
    ('B02.9', 'Herpes zóster sin complicaciones', 'Ciertas enfermedades infecciosas y parasitarias'),
    ('B34.9', 'Infección viral, no especificada', 'Ciertas enfermedades infecciosas y parasitarias'),
    ('B35.3', 'Tiña del pie [tinea pedis]', 'Ciertas enfermedades infecciosas y parasitarias'),
    ('B37.0', 'Estomatitis candidiásica', 'Ciertas enfermedades infecciosas y parasitarias'),
    ('B37.3', 'Candidiasis de la vulva y de la vagina', 'Ciertas enfermedades infecciosas y parasitarias'),
    ('B77.9', 'Ascariasis, no especificada', 'Ciertas enfermedades infecciosas y parasitarias'),
    ('B86', 'Escabiosis', 'Ciertas enfermedades infecciosas y parasitarias'),
    ('D50.9', 'Anemia por deficiencia de hierro sin otra especificación', 'Enfermedades de la sangre y de los órganos hematopoyéticos'),
    ('D51.9', 'Anemia por deficiencia de vitamina B12, sin otra especificación', 'Enfermedades de la sangre y de los órganos hematopoyéticos'),
    ('E03.9', 'Hipotiroidismo, no especificado', 'Enfermedades endocrinas, nutricionales y metabólicas'),
    ('E05.9', 'Tirotoxicosis, no especificada', 'Enfermedades endocrinas, nutricionales y metabólicas'),
    ('E10.9', 'Diabetes mellitus insulinodependiente, sin mención de complicación', 'Enfermedades endocrinas, nutricionales y metabólicas'),
    ('E11.9', 'Diabetes mellitus no insulinodependiente, sin mención de complicación', 'Enfermedades endocrinas, nutricionales y metabólicas'),
    ('E55.9', 'Deficiencia de vitamina D, no especificada', 'Enfermedades endocrinas, nutricionales y metabólicas'),
    ('E78.0', 'Hipercolesterolemia pura', 'Enfermedades endocrinas, nutricionales y metabólicas'),
    ('E78.5', 'Hiperlipidemia, no especificada', 'Enfermedades endocrinas, nutricionales y metabólicas'),
    ('E79.0', 'Hiperuricemia sin signos de artritis inflamatoria y enfermedad tofácea', 'Enfermedades endocrinas, nutricionales y metabólicas'),
    ('E86', 'Depleción del volumen', 'Enfermedades endocrinas, nutricionales y metabólicas'),
    ('F32.9', 'Episodio depresivo, no especificado', 'Trastornos mentales y del comportamiento'),
    ('F41.1', 'Trastorno de ansiedad generalizada', 'Trastornos mentales y del comportamiento'),
    ('F51.0', 'Insomnio no orgánico', 'Trastornos mentales y del comportamiento'),
    ('G40.9', 'Epilepsia, tipo no especificado', 'Enfermedades del sistema nervioso'),
    ('G43.9', 'Migraña, no especificada', 'Enfermedades del sistema nervioso'),
    ('G44.2', 'Cefalea debida a tensión', 'Enfermedades del sistema nervioso'),
    ('G47.0', 'Trastornos del inicio y del mantenimiento del sueño [insomnios]', 'Enfermedades del sistema nervioso'),
    ('G62.9', 'Polineuropatía, no especificada', 'Enfermedades del sistema nervioso'),
    ('H00.0', 'Orzuelo y otras inflamaciones profundas del párpado', 'Enfermedades del ojo y sus anexos'),
    ('H10.1', 'Conjuntivitis atópica aguda', 'Enfermedades del ojo y sus anexos'),
    ('H10.9', 'Conjuntivitis, no especificada', 'Enfermedades del ojo y sus anexos'),
    ('H60.9', 'Otitis externa, sin otra especificación', 'Enfermedades del oído y de la apófisis mastoides'),
    ('H66.9', 'Otitis media, no especificada', 'Enfermedades del oído y de la apófisis mastoides'),
    ('H81.1', 'Vértigo paroxístico benigno', 'Enfermedades del oído y de la apófisis mastoides'),
    ('I10', 'Hipertensión esencial (primaria)', 'Enfermedades del sistema circulatorio'),
    ('I11.9', 'Enfermedad cardíaca hipertensiva sin insuficiencia cardíaca (congestiva)', 'Enfermedades del sistema circulatorio'),
    ('I20.9', 'Angina de pecho, no especificada', 'Enfermedades del sistema circulatorio'),
    ('I25.1', 'Enfermedad aterosclerótica del corazón', 'Enfermedades del sistema circulatorio'),
    ('I48', 'Fibrilación y aleteo auricular', 'Enfermedades del sistema circulatorio'),
    ('I50.0', 'Insuficiencia cardíaca congestiva', 'Enfermedades del sistema circulatorio'),
    ('I63.9', 'Infarto cerebral, no especificado', 'Enfermedades del sistema circulatorio'),
    ('I80.2', 'Flebitis y tromboflebitis de otros vasos profundos de los miembros inferiores', 'Enfermedades del sistema circulatorio'),
    ('I83.9', 'Venas varicosas de los miembros inferiores sin úlcera ni inflamación', 'Enfermedades del sistema circulatorio'),
    ('J00', 'Rinofaringitis aguda [resfriado común]', 'Enfermedades del sistema respiratorio'),
    ('J01.9', 'Sinusitis aguda, no especificada', 'Enfermedades del sistema respiratorio'),
    ('J02.9', 'Faringitis aguda, no especificada', 'Enfermedades del sistema respiratorio'),
    ('J03.9', 'Amigdalitis aguda, no especificada', 'Enfermedades del sistema respiratorio'),
    ('J06.9', 'Infección aguda de las vías respiratorias superiores, no especificada', 'Enfermedades del sistema respiratorio'),
    ('J11.1', 'Influenza con otras manifestaciones respiratorias, virus no identificado', 'Enfermedades del sistema respiratorio'),
    ('J15.9', 'Neumonía bacteriana, no especificada', 'Enfermedades del sistema respiratorio'),
    ('J18.9', 'Neumonía, no especificada', 'Enfermedades del sistema respiratorio'),
    ('J20.9', 'Bronquitis aguda, no especificada', 'Enfermedades del sistema respiratorio'),
    ('J30.4', 'Rinitis alérgica, no especificada', 'Enfermedades del sistema respiratorio'),
    ('J44.9', 'Enfermedad pulmonar obstructiva crónica, no especificada', 'Enfermedades del sistema respiratorio'),
    ('J45.9', 'Asma, no especificado', 'Enfermedades del sistema respiratorio'),
    ('K04.7', 'Absceso periapical sin fístula', 'Enfermedades del sistema digestivo'),
    ('K12.0', 'Estomatitis aftosa recurrente', 'Enfermedades del sistema digestivo'),
    ('K21.0', 'Enfermedad del reflujo gastroesofágico con esofagitis', 'Enfermedades del sistema digestivo'),
    ('K21.9', 'Enfermedad del reflujo gastroesofágico sin esofagitis', 'Enfermedades del sistema digestivo'),
    ('K25.9', 'Úlcera gástrica, no especificada como aguda ni crónica, sin hemorragia ni perforación', 'Enfermedades del sistema digestivo'),
    ('K29.7', 'Gastritis, no especificada', 'Enfermedades del sistema digestivo'),
    ('K30', 'Dispepsia', 'Enfermedades del sistema digestivo'),
    ('K57.3', 'Enfermedad diverticular del intestino grueso sin perforación ni absceso', 'Enfermedades del sistema digestivo'),
    ('K58.9', 'Síndrome del colon irritable sin diarrea', 'Enfermedades del sistema digestivo'),
    ('K59.0', 'Constipación', 'Enfermedades del sistema digestivo'),
    ('K80.2', 'Cálculo de la vesícula biliar sin colecistitis', 'Enfermedades del sistema digestivo'),
    ('L01.0', 'Impétigo [cualquier sitio anatómico] [cualquier organismo]', 'Enfermedades de la piel y del tejido subcutáneo'),
    ('L03.9', 'Celulitis de sitio no especificado', 'Enfermedades de la piel y del tejido subcutáneo'),
    ('L20.9', 'Dermatitis atópica, no especificada', 'Enfermedades de la piel y del tejido subcutáneo'),
    ('L21.9', 'Dermatitis seborreica, no especificada', 'Enfermedades de la piel y del tejido subcutáneo'),
    ('L23.9', 'Dermatitis alérgica de contacto, de causa no especificada', 'Enfermedades de la piel y del tejido subcutáneo'),
    ('L40.0', 'Psoriasis vulgar', 'Enfermedades de la piel y del tejido subcutáneo'),
    ('L50.0', 'Urticaria alérgica', 'Enfermedades de la piel y del tejido subcutáneo'),
    ('L50.9', 'Urticaria, no especificada', 'Enfermedades de la piel y del tejido subcutáneo'),
    ('L70.0', 'Acné vulgar', 'Enfermedades de la piel y del tejido subcutáneo'),
    ('M06.9', 'Artritis reumatoide, no especificada', 'Enfermedades del sistema osteomuscular y del tejido conjuntivo'),
    ('M10.9', 'Gota, no especificada', 'Enfermedades del sistema osteomuscular y del tejido conjuntivo'),
    ('M15.9', 'Poliartrosis, no especificada', 'Enfermedades del sistema osteomuscular y del tejido conjuntivo'),
    ('M17.9', 'Gonartrosis, no especificada', 'Enfermedades del sistema osteomuscular y del tejido conjuntivo'),
    ('M25.5', 'Dolor en articulación', 'Enfermedades del sistema osteomuscular y del tejido conjuntivo'),
    ('M54.2', 'Cervicalgia', 'Enfermedades del sistema osteomuscular y del tejido conjuntivo'),
    ('M54.5', 'Lumbago no especificado', 'Enfermedades del sistema osteomuscular y del tejido conjuntivo'),
    ('M77.1', 'Epicondilitis lateral', 'Enfermedades del sistema osteomuscular y del tejido conjuntivo'),
    ('M79.1', 'Mialgia', 'Enfermedades del sistema osteomuscular y del tejido conjuntivo'),
    ('M81.0', 'Osteoporosis postmenopáusica', 'Enfermedades del sistema osteomuscular y del tejido conjuntivo'),
    ('N10', 'Nefritis tubulointersticial aguda', 'Enfermedades del sistema genitourinario'),
    ('N20.0', 'Cálculo del riñón', 'Enfermedades del sistema genitourinario'),
    ('N30.0', 'Cistitis aguda', 'Enfermedades del sistema genitourinario'),
    ('N39.0', 'Infección de vías urinarias, sitio no especificado', 'Enfermedades del sistema genitourinario'),
    ('N40', 'Hiperplasia de la próstata', 'Enfermedades del sistema genitourinario'),
    ('N41.0', 'Prostatitis aguda', 'Enfermedades del sistema genitourinario'),
    ('N76.0', 'Vaginitis aguda', 'Enfermedades del sistema genitourinario'),
    ('N94.6', 'Dismenorrea, no especificada', 'Enfermedades del sistema genitourinario'),
    ('R05', 'Tos', 'Síntomas, signos y hallazgos anormales clínicos y de laboratorio, no clasificados en otra parte'),
    ('R11', 'Náusea y vómito', 'Síntomas, signos y hallazgos anormales clínicos y de laboratorio, no clasificados en otra parte'),
    ('R50.9', 'Fiebre, no especificada', 'Síntomas, signos y hallazgos anormales clínicos y de laboratorio, no clasificados en otra parte'),
    ('R51', 'Cefalea', 'Síntomas, signos y hallazgos anormales clínicos y de laboratorio, no clasificados en otra parte')
ON CONFLICT (codigo) DO NOTHING;

-- 2. vademecum (100 filas). nombre no tiene UNIQUE: se evita el duplicado con NOT EXISTS.
INSERT INTO vademecum (nombre, composicion, funcion, presentacion, dosificacion, casa_comercial, contraindicaciones)
SELECT v.nombre, v.composicion, v.funcion, v.presentacion, v.dosificacion, v.casa_comercial, v.contraindicaciones
FROM (VALUES
    ('Paracetamol', 'Paracetamol 500 mg', 'Analgésico y antipirético', 'Caja x 20 tabletas', '500 mg a 1 g cada 6 a 8 horas; máximo 4 g al día', 'Laboratorios Ejemplo S.A.', 'Hipersensibilidad al paracetamol. Insuficiencia hepática grave.'),
    ('Ibuprofeno', 'Ibuprofeno 400 mg', 'Antiinflamatorio no esteroideo, analgésico y antipirético', 'Caja x 20 tabletas recubiertas', '400 mg cada 8 horas con alimentos', 'Laboratorios Ejemplo S.A.', 'Úlcera péptica activa. Insuficiencia renal o hepática grave. Tercer trimestre del embarazo. Hipersensibilidad a AINE.'),
    ('Naproxeno', 'Naproxeno sódico 550 mg', 'Antiinflamatorio no esteroideo y analgésico', 'Caja x 10 tabletas', '550 mg cada 12 horas con alimentos', 'Laboratorios Ejemplo S.A.', 'Úlcera péptica activa. Insuficiencia renal grave. Asma inducida por AINE.'),
    ('Diclofenaco', 'Diclofenaco sódico 50 mg', 'Antiinflamatorio no esteroideo y analgésico', 'Caja x 20 tabletas', '50 mg cada 8 a 12 horas', 'Laboratorios Ejemplo S.A.', 'Úlcera péptica activa. Insuficiencia cardíaca grave. Tercer trimestre del embarazo.'),
    ('Diclofenaco gel', 'Diclofenaco dietilamina 1,16 %', 'Antiinflamatorio tópico', 'Tubo x 60 g', 'Aplicar 3 a 4 veces al día en la zona afectada', 'Laboratorios Ejemplo S.A.', 'No aplicar sobre piel lesionada. Hipersensibilidad a AINE.'),
    ('Celecoxib', 'Celecoxib 200 mg', 'Antiinflamatorio inhibidor selectivo de la COX-2', 'Caja x 10 cápsulas', '200 mg una vez al día', 'Laboratorios Ejemplo S.A.', 'Cardiopatía isquémica establecida. Alergia a sulfonamidas. Úlcera péptica activa.'),
    ('Ciclobenzaprina', 'Ciclobenzaprina clorhidrato 10 mg', 'Relajante muscular de acción central', 'Caja x 20 tabletas', '10 mg cada 8 horas por un máximo de 3 semanas', 'Laboratorios Ejemplo S.A.', 'Uso concomitante de IMAO. Arritmias. Hipertiroidismo. Fase aguda posinfarto.'),
    ('Colchicina', 'Colchicina 0,5 mg', 'Antigotoso', 'Caja x 30 tabletas', '1 mg al inicio, 0,5 mg una hora después; luego 0,5 mg cada 12 horas', 'Laboratorios Ejemplo S.A.', 'Insuficiencia renal o hepática grave. Uso con inhibidores potentes de CYP3A4.'),
    ('Alopurinol', 'Alopurinol 300 mg', 'Hipouricemiante, inhibidor de la xantina oxidasa', 'Caja x 30 tabletas', '100 a 300 mg una vez al día', 'Laboratorios Ejemplo S.A.', 'No iniciar durante una crisis aguda de gota. Hipersensibilidad al alopurinol.'),
    ('Metotrexato', 'Metotrexato 2,5 mg', 'Inmunosupresor y antirreumático modificador de la enfermedad', 'Frasco x 50 tabletas', '7,5 a 15 mg una vez por semana', 'Laboratorios Ejemplo S.A.', 'Embarazo y lactancia. Insuficiencia hepática o renal grave. Discrasias sanguíneas.'),
    ('Prednisona', 'Prednisona 20 mg', 'Corticosteroide antiinflamatorio e inmunosupresor', 'Caja x 20 tabletas', '5 a 60 mg al día por la mañana según indicación', 'Laboratorios Ejemplo S.A.', 'Infecciones sistémicas no tratadas. Úlcera péptica activa.'),
    ('Alendronato', 'Ácido alendrónico 70 mg', 'Bifosfonato inhibidor de la resorción ósea', 'Caja x 4 tabletas', '70 mg una vez por semana en ayunas', 'Laboratorios Ejemplo S.A.', 'Anomalías del esófago. Imposibilidad de permanecer erguido 30 minutos. Hipocalcemia.'),
    ('Amoxicilina', 'Amoxicilina 500 mg', 'Antibiótico betalactámico (aminopenicilina)', 'Caja x 21 cápsulas', '500 mg cada 8 horas por 7 a 10 días', 'Farmacéutica Andina S.A.', 'Alergia a penicilinas. Mononucleosis infecciosa.'),
    ('Amoxicilina + ácido clavulánico', 'Amoxicilina 875 mg + ácido clavulánico 125 mg', 'Antibiótico betalactámico con inhibidor de betalactamasas', 'Caja x 14 tabletas', '875/125 mg cada 12 horas por 7 a 10 días', 'Farmacéutica Andina S.A.', 'Alergia a penicilinas. Antecedente de ictericia por amoxicilina con ácido clavulánico.'),
    ('Azitromicina', 'Azitromicina 500 mg', 'Antibiótico macrólido', 'Caja x 3 tabletas', '500 mg una vez al día por 3 días', 'Farmacéutica Andina S.A.', 'Hipersensibilidad a macrólidos. Prolongación del intervalo QT.'),
    ('Claritromicina', 'Claritromicina 500 mg', 'Antibiótico macrólido', 'Caja x 14 tabletas', '500 mg cada 12 horas', 'Farmacéutica Andina S.A.', 'Uso con colchicina, ergotamina o estatinas metabolizadas por CYP3A4. Prolongación del intervalo QT.'),
    ('Cefalexina', 'Cefalexina 500 mg', 'Antibiótico cefalosporina de primera generación', 'Caja x 20 cápsulas', '500 mg cada 6 a 8 horas', 'Farmacéutica Andina S.A.', 'Alergia a cefalosporinas.'),
    ('Ceftriaxona', 'Ceftriaxona sódica 1 g', 'Antibiótico cefalosporina de tercera generación', 'Frasco ampolla de 1 g con diluyente', '1 a 2 g una vez al día por vía IM o IV', 'Farmacéutica Andina S.A.', 'Alergia a cefalosporinas. Neonatos con hiperbilirrubinemia.'),
    ('Ciprofloxacino', 'Ciprofloxacino 500 mg', 'Antibiótico fluoroquinolona', 'Caja x 10 tabletas', '500 mg cada 12 horas', 'Farmacéutica Andina S.A.', 'Embarazo. Menores de 18 años salvo indicación expresa. Antecedente de tendinopatía por quinolonas.'),
    ('Levofloxacino', 'Levofloxacino 500 mg', 'Antibiótico fluoroquinolona', 'Caja x 7 tabletas', '500 a 750 mg una vez al día', 'Farmacéutica Andina S.A.', 'Epilepsia. Tendinopatía por quinolonas. Embarazo y lactancia.'),
    ('Nitrofurantoína', 'Nitrofurantoína macrocristales 100 mg', 'Antibacteriano urinario', 'Caja x 20 cápsulas', '100 mg cada 12 horas por 5 días', 'Farmacéutica Andina S.A.', 'Insuficiencia renal (depuración menor de 45 ml/min). Embarazo a término.'),
    ('Fosfomicina', 'Fosfomicina trometamol 3 g', 'Antibacteriano urinario', 'Caja x 1 sobre de granulado', '3 g en dosis única, en ayunas', 'Farmacéutica Andina S.A.', 'Insuficiencia renal grave. Hipersensibilidad a la fosfomicina.'),
    ('Clindamicina', 'Clindamicina 300 mg', 'Antibiótico lincosamida', 'Caja x 16 cápsulas', '300 mg cada 6 a 8 horas', 'Farmacéutica Andina S.A.', 'Antecedente de colitis seudomembranosa. Hipersensibilidad a lincosamidas.'),
    ('Doxiciclina', 'Doxiciclina 100 mg', 'Antibiótico tetraciclina', 'Caja x 10 cápsulas', '100 mg cada 12 horas', 'Farmacéutica Andina S.A.', 'Embarazo y lactancia. Menores de 8 años.'),
    ('Metronidazol', 'Metronidazol 500 mg', 'Antibacteriano y antiprotozoario (nitroimidazol)', 'Caja x 20 tabletas', '500 mg cada 8 a 12 horas', 'Farmacéutica Andina S.A.', 'Primer trimestre del embarazo. Consumo de alcohol durante el tratamiento.'),
    ('Aciclovir', 'Aciclovir 400 mg', 'Antiviral análogo de nucleósido', 'Caja x 35 tabletas', '800 mg cinco veces al día por 7 días', 'Laboratorios Austral S.A.', 'Hipersensibilidad al aciclovir o al valaciclovir.'),
    ('Oseltamivir', 'Oseltamivir 75 mg', 'Antiviral inhibidor de la neuraminidasa', 'Caja x 10 cápsulas', '75 mg cada 12 horas por 5 días', 'Laboratorios Austral S.A.', 'Hipersensibilidad al oseltamivir.'),
    ('Fluconazol', 'Fluconazol 150 mg', 'Antifúngico triazólico', 'Caja x 1 cápsula', '150 mg en dosis única', 'Laboratorios Austral S.A.', 'Uso con terfenadina o cisaprida. Embarazo.'),
    ('Nistatina', 'Nistatina 100 000 UI/ml', 'Antifúngico poliénico', 'Frasco x 60 ml de suspensión oral', '4 a 6 ml cada 6 horas', 'Laboratorios Austral S.A.', 'Hipersensibilidad a la nistatina.'),
    ('Clotrimazol óvulos', 'Clotrimazol 500 mg', 'Antifúngico imidazólico de uso vaginal', 'Caja x 1 óvulo vaginal', '500 mg por vía vaginal en dosis única, por la noche', 'Laboratorios Austral S.A.', 'Hipersensibilidad a imidazoles.'),
    ('Albendazol', 'Albendazol 400 mg', 'Antihelmíntico', 'Caja x 1 tableta', '400 mg en dosis única', 'Laboratorios Austral S.A.', 'Embarazo. Hipersensibilidad a benzimidazoles.'),
    ('Tamsulosina', 'Tamsulosina clorhidrato 0,4 mg', 'Bloqueador alfa-1 adrenérgico', 'Caja x 30 cápsulas de liberación prolongada', '0,4 mg una vez al día después del desayuno', 'Laboratorios Austral S.A.', 'Hipotensión ortostática. Insuficiencia hepática grave.'),
    ('Tobramicina oftálmica', 'Tobramicina 0,3 %', 'Antibiótico aminoglucósido oftálmico', 'Frasco gotero x 5 ml', '1 a 2 gotas en el ojo afectado cada 4 horas', 'Laboratorios Austral S.A.', 'Hipersensibilidad a aminoglucósidos.'),
    ('Olopatadina oftálmica', 'Olopatadina 0,1 %', 'Antihistamínico y estabilizador de mastocitos oftálmico', 'Frasco gotero x 5 ml', '1 gota en cada ojo cada 12 horas', 'Laboratorios Austral S.A.', 'Hipersensibilidad a la olopatadina.'),
    ('Ciprofloxacino + hidrocortisona ótico', 'Ciprofloxacino 0,2 % + hidrocortisona 1 %', 'Antibiótico y corticosteroide ótico', 'Frasco gotero x 10 ml', '3 gotas en el oído afectado cada 12 horas por 7 días', 'Laboratorios Austral S.A.', 'Perforación de la membrana timpánica. Infecciones virales del conducto auditivo.'),
    ('Losartán', 'Losartán potásico 50 mg', 'Antihipertensivo antagonista del receptor de angiotensina II', 'Caja x 30 tabletas', '50 mg una vez al día', 'Laboratorios Cóndor S.A.', 'Embarazo. Uso con aliskireno en pacientes diabéticos.'),
    ('Enalapril', 'Enalapril maleato 10 mg', 'Antihipertensivo inhibidor de la ECA', 'Caja x 30 tabletas', '10 a 20 mg una vez al día', 'Laboratorios Cóndor S.A.', 'Embarazo. Antecedente de angioedema.'),
    ('Amlodipino', 'Amlodipino 5 mg', 'Antihipertensivo bloqueador de los canales de calcio', 'Caja x 30 tabletas', '5 a 10 mg una vez al día', 'Laboratorios Cóndor S.A.', 'Hipotensión grave. Choque cardiogénico. Estenosis aórtica grave.'),
    ('Hidroclorotiazida', 'Hidroclorotiazida 25 mg', 'Diurético tiazídico', 'Caja x 30 tabletas', '12,5 a 25 mg una vez al día por la mañana', 'Laboratorios Cóndor S.A.', 'Anuria. Insuficiencia renal grave. Hipopotasemia refractaria.'),
    ('Bisoprolol', 'Bisoprolol fumarato 5 mg', 'Betabloqueador cardioselectivo', 'Caja x 30 tabletas', '2,5 a 10 mg una vez al día', 'Laboratorios Cóndor S.A.', 'Bradicardia sintomática. Bloqueo auriculoventricular de segundo o tercer grado. Asma grave.'),
    ('Furosemida', 'Furosemida 40 mg', 'Diurético de asa', 'Caja x 20 tabletas', '20 a 80 mg al día por la mañana', 'Laboratorios Cóndor S.A.', 'Anuria. Hipopotasemia grave. Deshidratación.'),
    ('Espironolactona', 'Espironolactona 25 mg', 'Diurético ahorrador de potasio, antagonista de la aldosterona', 'Caja x 30 tabletas', '25 a 50 mg una vez al día', 'Laboratorios Cóndor S.A.', 'Hiperpotasemia. Insuficiencia renal grave. Enfermedad de Addison.'),
    ('Atorvastatina', 'Atorvastatina 20 mg', 'Hipolipemiante inhibidor de la HMG-CoA reductasa', 'Caja x 30 tabletas', '10 a 80 mg una vez al día', 'Laboratorios Cóndor S.A.', 'Enfermedad hepática activa. Embarazo y lactancia.'),
    ('Rosuvastatina', 'Rosuvastatina 10 mg', 'Hipolipemiante inhibidor de la HMG-CoA reductasa', 'Caja x 30 tabletas', '5 a 20 mg una vez al día', 'Laboratorios Cóndor S.A.', 'Enfermedad hepática activa. Miopatía. Embarazo.'),
    ('Ácido acetilsalicílico', 'Ácido acetilsalicílico 100 mg', 'Antiagregante plaquetario', 'Caja x 30 tabletas con cubierta entérica', '100 mg una vez al día con alimentos', 'Laboratorios Cóndor S.A.', 'Úlcera péptica activa. Hemofilia. Menores de 16 años.'),
    ('Clopidogrel', 'Clopidogrel 75 mg', 'Antiagregante plaquetario', 'Caja x 28 tabletas', '75 mg una vez al día', 'Laboratorios Cóndor S.A.', 'Sangrado activo. Insuficiencia hepática grave.'),
    ('Warfarina', 'Warfarina sódica 5 mg', 'Anticoagulante oral antagonista de la vitamina K', 'Caja x 30 tabletas', 'Dosis ajustada según INR (objetivo de 2 a 3)', 'Laboratorios Cóndor S.A.', 'Embarazo. Sangrado activo. Hipertensión grave no controlada.'),
    ('Enoxaparina', 'Enoxaparina sódica 40 mg/0,4 ml', 'Anticoagulante, heparina de bajo peso molecular', 'Caja x 2 jeringas prellenadas', '1 mg/kg cada 12 horas por vía subcutánea', 'Laboratorios Cóndor S.A.', 'Sangrado activo. Trombocitopenia inducida por heparina.'),
    ('Diosmina + hesperidina', 'Diosmina 450 mg + hesperidina 50 mg', 'Venotónico y protector vascular', 'Caja x 30 tabletas', '1 tableta cada 12 horas con alimentos', 'Laboratorios Cóndor S.A.', 'Hipersensibilidad a los componentes.'),
    ('Metformina', 'Metformina clorhidrato 850 mg', 'Antidiabético oral (biguanida)', 'Caja x 30 tabletas', '850 mg una o dos veces al día con alimentos', 'BioFarma Equinoccio S.A.', 'Filtrado glomerular menor de 30 ml/min. Acidosis metabólica. Uso de contraste yodado.'),
    ('Glibenclamida', 'Glibenclamida 5 mg', 'Antidiabético oral (sulfonilurea)', 'Caja x 30 tabletas', '2,5 a 10 mg al día antes del desayuno', 'BioFarma Equinoccio S.A.', 'Diabetes tipo 1. Cetoacidosis. Insuficiencia renal o hepática grave.'),
    ('Empagliflozina', 'Empagliflozina 10 mg', 'Antidiabético oral inhibidor de SGLT2', 'Caja x 30 tabletas', '10 a 25 mg una vez al día por la mañana', 'BioFarma Equinoccio S.A.', 'Diabetes tipo 1. Cetoacidosis diabética. Diálisis.'),
    ('Insulina glargina', 'Insulina glargina 100 UI/ml', 'Insulina basal de acción prolongada', 'Caja x 1 pluma prellenada de 3 ml', 'Dosis individual una vez al día por vía subcutánea', 'BioFarma Equinoccio S.A.', 'Hipoglucemia. Hipersensibilidad a la insulina glargina.'),
    ('Insulina asparta', 'Insulina asparta 100 UI/ml', 'Insulina de acción rápida', 'Caja x 1 pluma prellenada de 3 ml', 'Dosis individual antes de cada comida por vía subcutánea', 'BioFarma Equinoccio S.A.', 'Hipoglucemia. Hipersensibilidad a la insulina asparta.'),
    ('Levotiroxina', 'Levotiroxina sódica 100 mcg', 'Hormona tiroidea', 'Caja x 50 tabletas', '25 a 200 mcg una vez al día en ayunas', 'BioFarma Equinoccio S.A.', 'Tirotoxicosis no tratada. Infarto agudo de miocardio. Insuficiencia suprarrenal no corregida.'),
    ('Metimazol', 'Tiamazol 5 mg', 'Antitiroideo', 'Caja x 50 tabletas', '10 a 40 mg al día en dosis divididas', 'BioFarma Equinoccio S.A.', 'Agranulocitosis previa por tiamazol. Primer trimestre del embarazo.'),
    ('Colecalciferol', 'Colecalciferol (vitamina D3) 50 000 UI', 'Suplemento de vitamina D', 'Caja x 4 cápsulas blandas', '50 000 UI una vez por semana', 'BioFarma Equinoccio S.A.', 'Hipercalcemia. Hipervitaminosis D.'),
    ('Carbonato de calcio + vitamina D3', 'Carbonato de calcio 1 500 mg (600 mg de calcio) + colecalciferol 400 UI', 'Suplemento de calcio y vitamina D', 'Frasco x 60 tabletas', '1 tableta cada 12 horas con alimentos', 'BioFarma Equinoccio S.A.', 'Hipercalcemia. Litiasis renal cálcica.'),
    ('Sulfato ferroso', 'Sulfato ferroso 300 mg (60 mg de hierro elemental)', 'Antianémico, suplemento de hierro', 'Caja x 30 tabletas', '1 tableta una o dos veces al día', 'BioFarma Equinoccio S.A.', 'Hemocromatosis. Anemias no ferropénicas.'),
    ('Cianocobalamina', 'Cianocobalamina 1 000 mcg/ml', 'Vitamina B12', 'Caja x 3 ampollas de 1 ml', '1 000 mcg IM cada semana y luego cada mes', 'BioFarma Equinoccio S.A.', 'Hipersensibilidad a la cobalamina.'),
    ('Ácido fólico', 'Ácido fólico 1 mg', 'Vitamina del complejo B, antianémico', 'Caja x 30 tabletas', '1 a 5 mg una vez al día', 'BioFarma Equinoccio S.A.', 'Anemia por déficit de vitamina B12 no tratada.'),
    ('Omeprazol', 'Omeprazol 20 mg', 'Inhibidor de la bomba de protones', 'Caja x 14 cápsulas', '20 a 40 mg una vez al día en ayunas', 'Genéricos del Pacífico Cía. Ltda.', 'Uso con nelfinavir. Hipersensibilidad a benzimidazoles.'),
    ('Esomeprazol', 'Esomeprazol 40 mg', 'Inhibidor de la bomba de protones', 'Caja x 14 tabletas', '40 mg una vez al día por 4 a 8 semanas', 'Genéricos del Pacífico Cía. Ltda.', 'Uso con nelfinavir.'),
    ('Hidróxido de aluminio + magnesio', 'Hidróxido de aluminio 400 mg + hidróxido de magnesio 400 mg / 10 ml', 'Antiácido', 'Frasco x 360 ml de suspensión', '10 a 20 ml después de las comidas y al acostarse', 'Genéricos del Pacífico Cía. Ltda.', 'Insuficiencia renal grave. Hipofosfatemia.'),
    ('Metoclopramida', 'Metoclopramida 10 mg', 'Antiemético y procinético', 'Caja x 20 tabletas', '10 mg hasta 3 veces al día por un máximo de 5 días', 'Genéricos del Pacífico Cía. Ltda.', 'Feocromocitoma. Obstrucción o hemorragia gastrointestinal. Epilepsia.'),
    ('Simeticona', 'Simeticona 80 mg', 'Antiflatulento', 'Caja x 30 tabletas masticables', '80 mg después de cada comida', 'Genéricos del Pacífico Cía. Ltda.', 'Obstrucción intestinal.'),
    ('Butilescopolamina', 'Butilbromuro de hioscina 10 mg', 'Antiespasmódico', 'Caja x 20 grageas', '10 a 20 mg cada 8 horas', 'Genéricos del Pacífico Cía. Ltda.', 'Glaucoma de ángulo cerrado. Miastenia grave. Megacolon.'),
    ('Lactulosa', 'Lactulosa 3,33 g/5 ml', 'Laxante osmótico', 'Frasco x 200 ml de jarabe', '15 a 30 ml una vez al día', 'Genéricos del Pacífico Cía. Ltda.', 'Galactosemia. Obstrucción intestinal.'),
    ('Polietilenglicol 3350', 'Macrogol 3350, 17 g por sobre', 'Laxante osmótico', 'Caja x 20 sobres', '17 g disueltos en un vaso de agua una vez al día', 'Genéricos del Pacífico Cía. Ltda.', 'Obstrucción o perforación intestinal. Enfermedad inflamatoria intestinal grave.'),
    ('Ácido ursodesoxicólico', 'Ácido ursodesoxicólico 250 mg', 'Litolítico biliar y colerético', 'Caja x 30 cápsulas', '8 a 10 mg/kg al día', 'Genéricos del Pacífico Cía. Ltda.', 'Cálculos calcificados. Colecistitis aguda. Obstrucción biliar.'),
    ('Sales de rehidratación oral', 'Glucosa, cloruro de sodio, cloruro de potasio y citrato trisódico', 'Rehidratante oral de osmolaridad reducida', 'Caja x 10 sobres', '1 sobre en 1 litro de agua; tomar a libre demanda', 'Genéricos del Pacífico Cía. Ltda.', 'Obstrucción intestinal. Vómitos incoercibles. Choque.'),
    ('Salbutamol', 'Salbutamol 100 mcg/dosis', 'Broncodilatador agonista beta-2 de acción corta', 'Inhalador presurizado x 200 dosis', '1 a 2 inhalaciones cada 4 a 6 horas según necesidad', 'Respira Pharma S.A.', 'Hipersensibilidad al salbutamol.'),
    ('Budesonida inhalada', 'Budesonida 200 mcg/dosis', 'Corticosteroide inhalado', 'Inhalador x 200 dosis', '200 a 400 mcg cada 12 horas', 'Respira Pharma S.A.', 'Tuberculosis pulmonar activa no tratada.'),
    ('Montelukast', 'Montelukast 10 mg', 'Antagonista de los receptores de leucotrienos', 'Caja x 30 tabletas', '10 mg una vez al día por la noche', 'Respira Pharma S.A.', 'Hipersensibilidad al montelukast.'),
    ('Salmeterol + fluticasona', 'Salmeterol 50 mcg + propionato de fluticasona 250 mcg por dosis', 'Broncodilatador de acción prolongada con corticosteroide inhalado', 'Dispositivo inhalador x 60 dosis', '1 inhalación cada 12 horas', 'Respira Pharma S.A.', 'No usar para tratar una crisis aguda. Hipersensibilidad a los componentes.'),
    ('Tiotropio', 'Bromuro de tiotropio 18 mcg', 'Broncodilatador anticolinérgico de acción prolongada', 'Caja x 30 cápsulas para inhalación', '1 cápsula inhalada una vez al día', 'Respira Pharma S.A.', 'Hipersensibilidad a la atropina o derivados. Glaucoma de ángulo cerrado.'),
    ('Mometasona nasal', 'Furoato de mometasona 50 mcg/dosis', 'Corticosteroide nasal', 'Spray nasal x 140 dosis', '2 aplicaciones en cada fosa nasal una vez al día', 'Respira Pharma S.A.', 'Infección nasal no tratada. Cirugía nasal reciente.'),
    ('Cloruro de sodio nasal', 'Cloruro de sodio 0,9 %', 'Humectante y descongestionante nasal', 'Spray nasal x 30 ml', '2 a 3 aplicaciones en cada fosa nasal según necesidad', 'Respira Pharma S.A.', NULL),
    ('Ambroxol', 'Ambroxol clorhidrato 30 mg/5 ml', 'Mucolítico y expectorante', 'Frasco x 120 ml de jarabe', '5 a 10 ml cada 8 horas', 'Respira Pharma S.A.', 'Úlcera péptica activa. Primer trimestre del embarazo.'),
    ('Loratadina', 'Loratadina 10 mg', 'Antihistamínico H1 no sedante', 'Caja x 10 tabletas', '10 mg una vez al día', 'Respira Pharma S.A.', 'Hipersensibilidad a la loratadina. Menores de 2 años.'),
    ('Cetirizina', 'Cetirizina diclorhidrato 10 mg', 'Antihistamínico H1', 'Caja x 10 tabletas', '10 mg una vez al día', 'Respira Pharma S.A.', 'Insuficiencia renal grave. Hipersensibilidad a la hidroxizina.'),
    ('Desloratadina', 'Desloratadina 5 mg', 'Antihistamínico H1 no sedante', 'Caja x 10 tabletas', '5 mg una vez al día', 'Respira Pharma S.A.', 'Hipersensibilidad a la desloratadina o a la loratadina.'),
    ('Hidrocortisona crema', 'Acetato de hidrocortisona 1 %', 'Corticosteroide tópico de baja potencia', 'Tubo x 20 g', 'Aplicar una capa fina 2 veces al día', 'Dermalab Química S.A.', 'Infecciones cutáneas virales, fúngicas o bacterianas no tratadas. Rosácea.'),
    ('Betametasona crema', 'Valerato de betametasona 0,1 %', 'Corticosteroide tópico de potencia media', 'Tubo x 30 g', 'Aplicar 1 a 2 veces al día por un máximo de 2 semanas', 'Dermalab Química S.A.', 'Infecciones cutáneas no tratadas. Acné. Rosácea.'),
    ('Mupirocina', 'Mupirocina 2 %', 'Antibiótico tópico', 'Tubo x 15 g de ungüento', 'Aplicar 3 veces al día por 5 a 10 días', 'Dermalab Química S.A.', 'Hipersensibilidad a la mupirocina.'),
    ('Clotrimazol crema', 'Clotrimazol 1 %', 'Antifúngico tópico imidazólico', 'Tubo x 20 g', 'Aplicar 2 a 3 veces al día por 2 a 4 semanas', 'Dermalab Química S.A.', 'Hipersensibilidad a imidazoles.'),
    ('Ketoconazol crema', 'Ketoconazol 2 %', 'Antifúngico tópico imidazólico', 'Tubo x 30 g', 'Aplicar 1 a 2 veces al día', 'Dermalab Química S.A.', 'Hipersensibilidad al ketoconazol.'),
    ('Permetrina', 'Permetrina 5 %', 'Escabicida y pediculicida', 'Frasco x 60 ml de loción', 'Aplicar en todo el cuerpo, dejar 8 a 14 horas y enjuagar; repetir a los 7 días', 'Dermalab Química S.A.', 'Hipersensibilidad a piretroides. Menores de 2 meses.'),
    ('Peróxido de benzoilo', 'Peróxido de benzoilo 5 %', 'Antiacneico queratolítico y antibacteriano', 'Tubo x 30 g de gel', 'Aplicar una vez al día por la noche', 'Dermalab Química S.A.', 'Hipersensibilidad al peróxido de benzoilo.'),
    ('Triamcinolona orabase', 'Acetónido de triamcinolona 0,1 % en pasta adhesiva', 'Corticosteroide de uso bucal', 'Tubo x 5 g de pasta', 'Aplicar sobre la lesión 2 a 3 veces al día', 'Dermalab Química S.A.', 'Infecciones bucales fúngicas, virales o bacterianas no tratadas.'),
    ('Clorhexidina enjuague', 'Gluconato de clorhexidina 0,12 %', 'Antiséptico bucal', 'Frasco x 250 ml', 'Enjuagar con 15 ml por 30 segundos cada 12 horas', 'Dermalab Química S.A.', 'Hipersensibilidad a la clorhexidina.'),
    ('Sertralina', 'Sertralina 50 mg', 'Antidepresivo inhibidor selectivo de la recaptación de serotonina', 'Caja x 30 tabletas', '50 a 200 mg una vez al día', 'Neurofarma del Sur S.A.', 'Uso con IMAO o pimozida.'),
    ('Escitalopram', 'Escitalopram 10 mg', 'Antidepresivo inhibidor selectivo de la recaptación de serotonina', 'Caja x 28 tabletas', '10 a 20 mg una vez al día', 'Neurofarma del Sur S.A.', 'Uso con IMAO. Prolongación del intervalo QT.'),
    ('Zolpidem', 'Zolpidem tartrato 10 mg', 'Hipnótico no benzodiazepínico', 'Caja x 10 tabletas', '5 a 10 mg al acostarse, por tiempo limitado', 'Neurofarma del Sur S.A.', 'Apnea del sueño. Insuficiencia respiratoria o hepática grave. Miastenia grave.'),
    ('Sumatriptán', 'Sumatriptán 50 mg', 'Antimigrañoso agonista de receptores 5-HT1', 'Caja x 2 tabletas', '50 mg al inicio de la crisis; repetir a las 2 horas si es necesario', 'Neurofarma del Sur S.A.', 'Cardiopatía isquémica. Hipertensión no controlada. Uso con ergotamínicos.'),
    ('Carbamazepina', 'Carbamazepina 200 mg', 'Anticonvulsivante y analgésico del dolor neuropático', 'Caja x 30 tabletas', '200 a 400 mg cada 12 horas', 'Neurofarma del Sur S.A.', 'Bloqueo auriculoventricular. Depresión de la médula ósea. Uso con IMAO.'),
    ('Ácido valproico', 'Valproato de sodio 500 mg', 'Anticonvulsivante', 'Caja x 30 tabletas de liberación prolongada', '500 a 1 000 mg cada 12 horas', 'Neurofarma del Sur S.A.', 'Hepatopatía. Embarazo. Trastornos del ciclo de la urea.'),
    ('Gabapentina', 'Gabapentina 300 mg', 'Anticonvulsivante y analgésico del dolor neuropático', 'Caja x 30 cápsulas', '300 mg cada 8 horas, con ajuste según respuesta', 'Neurofarma del Sur S.A.', 'Hipersensibilidad a la gabapentina.'),
    ('Betahistina', 'Betahistina diclorhidrato 16 mg', 'Antivertiginoso', 'Caja x 30 tabletas', '16 mg cada 8 horas', 'Neurofarma del Sur S.A.', 'Feocromocitoma.'),
    ('Dimenhidrinato', 'Dimenhidrinato 50 mg', 'Antiemético y antivertiginoso', 'Caja x 12 tabletas', '50 mg cada 6 a 8 horas', 'Neurofarma del Sur S.A.', 'Glaucoma de ángulo cerrado. Retención urinaria. Menores de 2 años.')
) AS v (nombre, composicion, funcion, presentacion, dosificacion, casa_comercial, contraindicaciones)
WHERE NOT EXISTS (SELECT 1 FROM vademecum x WHERE x.nombre = v.nombre);

-- 3. vademecum_cie10 (244 filas). La pareja es PRIMARY KEY (id_vademecum, id_cie10).
INSERT INTO vademecum_cie10 (id_vademecum, id_cie10)
SELECT v.id, c.id
FROM (VALUES
    ('A07.1', 'Metronidazol'),
    ('A08.4', 'Sales de rehidratación oral'),
    ('A09', 'Sales de rehidratación oral'),
    ('A09', 'Metronidazol'),
    ('A90', 'Paracetamol'),
    ('A90', 'Sales de rehidratación oral'),
    ('B01.9', 'Aciclovir'),
    ('B01.9', 'Paracetamol'),
    ('B01.9', 'Cetirizina'),
    ('B02.9', 'Aciclovir'),
    ('B02.9', 'Paracetamol'),
    ('B02.9', 'Gabapentina'),
    ('B34.9', 'Paracetamol'),
    ('B34.9', 'Ibuprofeno'),
    ('B35.3', 'Clotrimazol crema'),
    ('B35.3', 'Ketoconazol crema'),
    ('B37.0', 'Nistatina'),
    ('B37.0', 'Fluconazol'),
    ('B37.3', 'Fluconazol'),
    ('B37.3', 'Clotrimazol óvulos'),
    ('B77.9', 'Albendazol'),
    ('B86', 'Permetrina'),
    ('B86', 'Cetirizina'),
    ('D50.9', 'Sulfato ferroso'),
    ('D50.9', 'Ácido fólico'),
    ('D51.9', 'Cianocobalamina'),
    ('D51.9', 'Ácido fólico'),
    ('E03.9', 'Levotiroxina'),
    ('E05.9', 'Metimazol'),
    ('E10.9', 'Insulina glargina'),
    ('E10.9', 'Insulina asparta'),
    ('E11.9', 'Metformina'),
    ('E11.9', 'Glibenclamida'),
    ('E11.9', 'Empagliflozina'),
    ('E11.9', 'Insulina glargina'),
    ('E55.9', 'Colecalciferol'),
    ('E55.9', 'Carbonato de calcio + vitamina D3'),
    ('E78.0', 'Atorvastatina'),
    ('E78.0', 'Rosuvastatina'),
    ('E78.5', 'Atorvastatina'),
    ('E78.5', 'Rosuvastatina'),
    ('E79.0', 'Alopurinol'),
    ('E86', 'Sales de rehidratación oral'),
    ('F32.9', 'Sertralina'),
    ('F32.9', 'Escitalopram'),
    ('F41.1', 'Sertralina'),
    ('F41.1', 'Escitalopram'),
    ('F51.0', 'Zolpidem'),
    ('G40.9', 'Carbamazepina'),
    ('G40.9', 'Ácido valproico'),
    ('G43.9', 'Sumatriptán'),
    ('G43.9', 'Naproxeno'),
    ('G43.9', 'Ibuprofeno'),
    ('G43.9', 'Metoclopramida'),
    ('G44.2', 'Paracetamol'),
    ('G44.2', 'Ibuprofeno'),
    ('G44.2', 'Ciclobenzaprina'),
    ('G47.0', 'Zolpidem'),
    ('G62.9', 'Gabapentina'),
    ('G62.9', 'Carbamazepina'),
    ('H00.0', 'Tobramicina oftálmica'),
    ('H10.1', 'Olopatadina oftálmica'),
    ('H10.1', 'Loratadina'),
    ('H10.9', 'Tobramicina oftálmica'),
    ('H60.9', 'Ciprofloxacino + hidrocortisona ótico'),
    ('H60.9', 'Ibuprofeno'),
    ('H66.9', 'Amoxicilina'),
    ('H66.9', 'Amoxicilina + ácido clavulánico'),
    ('H66.9', 'Ibuprofeno'),
    ('H66.9', 'Paracetamol'),
    ('H81.1', 'Betahistina'),
    ('H81.1', 'Dimenhidrinato'),
    ('I10', 'Losartán'),
    ('I10', 'Enalapril'),
    ('I10', 'Amlodipino'),
    ('I10', 'Hidroclorotiazida'),
    ('I11.9', 'Losartán'),
    ('I11.9', 'Amlodipino'),
    ('I11.9', 'Bisoprolol'),
    ('I20.9', 'Ácido acetilsalicílico'),
    ('I20.9', 'Atorvastatina'),
    ('I20.9', 'Bisoprolol'),
    ('I25.1', 'Ácido acetilsalicílico'),
    ('I25.1', 'Clopidogrel'),
    ('I25.1', 'Atorvastatina'),
    ('I25.1', 'Bisoprolol'),
    ('I48', 'Warfarina'),
    ('I48', 'Bisoprolol'),
    ('I50.0', 'Furosemida'),
    ('I50.0', 'Espironolactona'),
    ('I50.0', 'Enalapril'),
    ('I50.0', 'Bisoprolol'),
    ('I63.9', 'Ácido acetilsalicílico'),
    ('I63.9', 'Clopidogrel'),
    ('I63.9', 'Atorvastatina'),
    ('I80.2', 'Enoxaparina'),
    ('I80.2', 'Warfarina'),
    ('I83.9', 'Diosmina + hesperidina'),
    ('J00', 'Paracetamol'),
    ('J00', 'Loratadina'),
    ('J00', 'Ibuprofeno'),
    ('J00', 'Cloruro de sodio nasal'),
    ('J01.9', 'Amoxicilina'),
    ('J01.9', 'Amoxicilina + ácido clavulánico'),
    ('J01.9', 'Mometasona nasal'),
    ('J01.9', 'Cloruro de sodio nasal'),
    ('J02.9', 'Amoxicilina'),
    ('J02.9', 'Ibuprofeno'),
    ('J02.9', 'Paracetamol'),
    ('J03.9', 'Amoxicilina'),
    ('J03.9', 'Azitromicina'),
    ('J03.9', 'Ibuprofeno'),
    ('J06.9', 'Paracetamol'),
    ('J06.9', 'Ibuprofeno'),
    ('J06.9', 'Loratadina'),
    ('J06.9', 'Cloruro de sodio nasal'),
    ('J11.1', 'Oseltamivir'),
    ('J11.1', 'Paracetamol'),
    ('J11.1', 'Ibuprofeno'),
    ('J15.9', 'Amoxicilina + ácido clavulánico'),
    ('J15.9', 'Azitromicina'),
    ('J15.9', 'Levofloxacino'),
    ('J15.9', 'Ceftriaxona'),
    ('J18.9', 'Amoxicilina'),
    ('J18.9', 'Azitromicina'),
    ('J18.9', 'Claritromicina'),
    ('J18.9', 'Levofloxacino'),
    ('J20.9', 'Ambroxol'),
    ('J20.9', 'Salbutamol'),
    ('J20.9', 'Paracetamol'),
    ('J30.4', 'Loratadina'),
    ('J30.4', 'Cetirizina'),
    ('J30.4', 'Desloratadina'),
    ('J30.4', 'Mometasona nasal'),
    ('J44.9', 'Salbutamol'),
    ('J44.9', 'Tiotropio'),
    ('J44.9', 'Salmeterol + fluticasona'),
    ('J45.9', 'Salbutamol'),
    ('J45.9', 'Budesonida inhalada'),
    ('J45.9', 'Montelukast'),
    ('J45.9', 'Salmeterol + fluticasona'),
    ('K04.7', 'Amoxicilina'),
    ('K04.7', 'Clindamicina'),
    ('K04.7', 'Ibuprofeno'),
    ('K12.0', 'Triamcinolona orabase'),
    ('K12.0', 'Clorhexidina enjuague'),
    ('K21.0', 'Omeprazol'),
    ('K21.0', 'Esomeprazol'),
    ('K21.9', 'Omeprazol'),
    ('K21.9', 'Esomeprazol'),
    ('K21.9', 'Hidróxido de aluminio + magnesio'),
    ('K25.9', 'Omeprazol'),
    ('K25.9', 'Amoxicilina'),
    ('K25.9', 'Claritromicina'),
    ('K29.7', 'Omeprazol'),
    ('K29.7', 'Hidróxido de aluminio + magnesio'),
    ('K30', 'Omeprazol'),
    ('K30', 'Simeticona'),
    ('K30', 'Metoclopramida'),
    ('K57.3', 'Ciprofloxacino'),
    ('K57.3', 'Metronidazol'),
    ('K58.9', 'Butilescopolamina'),
    ('K58.9', 'Simeticona'),
    ('K59.0', 'Lactulosa'),
    ('K59.0', 'Polietilenglicol 3350'),
    ('K80.2', 'Ácido ursodesoxicólico'),
    ('K80.2', 'Butilescopolamina'),
    ('L01.0', 'Mupirocina'),
    ('L01.0', 'Cefalexina'),
    ('L03.9', 'Cefalexina'),
    ('L03.9', 'Clindamicina'),
    ('L20.9', 'Hidrocortisona crema'),
    ('L20.9', 'Betametasona crema'),
    ('L20.9', 'Cetirizina'),
    ('L21.9', 'Ketoconazol crema'),
    ('L23.9', 'Betametasona crema'),
    ('L23.9', 'Loratadina'),
    ('L40.0', 'Betametasona crema'),
    ('L40.0', 'Metotrexato'),
    ('L50.0', 'Loratadina'),
    ('L50.0', 'Cetirizina'),
    ('L50.0', 'Desloratadina'),
    ('L50.0', 'Prednisona'),
    ('L50.9', 'Loratadina'),
    ('L50.9', 'Desloratadina'),
    ('L70.0', 'Peróxido de benzoilo'),
    ('L70.0', 'Doxiciclina'),
    ('M06.9', 'Metotrexato'),
    ('M06.9', 'Ácido fólico'),
    ('M06.9', 'Prednisona'),
    ('M10.9', 'Colchicina'),
    ('M10.9', 'Alopurinol'),
    ('M10.9', 'Naproxeno'),
    ('M15.9', 'Paracetamol'),
    ('M15.9', 'Celecoxib'),
    ('M17.9', 'Paracetamol'),
    ('M17.9', 'Celecoxib'),
    ('M17.9', 'Diclofenaco gel'),
    ('M25.5', 'Paracetamol'),
    ('M25.5', 'Naproxeno'),
    ('M25.5', 'Diclofenaco gel'),
    ('M54.2', 'Ibuprofeno'),
    ('M54.2', 'Diclofenaco'),
    ('M54.2', 'Ciclobenzaprina'),
    ('M54.5', 'Ibuprofeno'),
    ('M54.5', 'Diclofenaco'),
    ('M54.5', 'Naproxeno'),
    ('M54.5', 'Ciclobenzaprina'),
    ('M77.1', 'Diclofenaco gel'),
    ('M77.1', 'Ibuprofeno'),
    ('M79.1', 'Paracetamol'),
    ('M79.1', 'Ibuprofeno'),
    ('M79.1', 'Diclofenaco gel'),
    ('M81.0', 'Alendronato'),
    ('M81.0', 'Carbonato de calcio + vitamina D3'),
    ('M81.0', 'Colecalciferol'),
    ('N10', 'Ciprofloxacino'),
    ('N10', 'Levofloxacino'),
    ('N10', 'Ceftriaxona'),
    ('N20.0', 'Tamsulosina'),
    ('N20.0', 'Diclofenaco'),
    ('N20.0', 'Butilescopolamina'),
    ('N30.0', 'Nitrofurantoína'),
    ('N30.0', 'Fosfomicina'),
    ('N39.0', 'Nitrofurantoína'),
    ('N39.0', 'Fosfomicina'),
    ('N39.0', 'Ciprofloxacino'),
    ('N39.0', 'Cefalexina'),
    ('N40', 'Tamsulosina'),
    ('N41.0', 'Ciprofloxacino'),
    ('N41.0', 'Levofloxacino'),
    ('N76.0', 'Metronidazol'),
    ('N76.0', 'Clotrimazol óvulos'),
    ('N76.0', 'Fluconazol'),
    ('N94.6', 'Ibuprofeno'),
    ('N94.6', 'Naproxeno'),
    ('N94.6', 'Butilescopolamina'),
    ('R05', 'Ambroxol'),
    ('R11', 'Metoclopramida'),
    ('R11', 'Dimenhidrinato'),
    ('R50.9', 'Paracetamol'),
    ('R50.9', 'Ibuprofeno'),
    ('R51', 'Paracetamol'),
    ('R51', 'Ibuprofeno')
) AS r (codigo, nombre)
JOIN cie10 c ON c.codigo = r.codigo
JOIN vademecum v ON v.nombre = r.nombre
ON CONFLICT (id_vademecum, id_cie10) DO NOTHING;
